server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs