eureka:
  instance:
    hostname: localhost
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka

name:
  value: serhat
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0