server:
  port: 8040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/creditCard
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
